# Generated by Django 5.2.5 on 2025-09-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("external_id", models.CharField(db_index=True, max_length=128)),
                (
                    "source",
                    models.CharField(
                        choices=[("csv", "CSV"), ("json", "JSON"), ("xml", "XML")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("category", models.CharField(db_index=True, max_length=64)),
                ("ratings_raw", models.JSONField(blank=True, null=True)),
                (
                    "avg_rating",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=3),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category", "avg_rating"],
                        name="ingest_poin_categor_e2ab7c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("external_id", "source"),
                        name="unique_external_id_source",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("avg_rating__gte", 0), ("avg_rating__lte", 5)
                        ),
                        name="avg_rating_range_check",
                    ),
                ],
            },
        ),
    ]
